// Decompiled with JetBrains decompiler
// Type: NFCL_Handler.NFCL_Params
// Assembly: NFCL_Handler, Version=2.3.2.0, Culture=neutral, PublicKeyToken=f5405c50fba4c3ca
// MVID: 887E21A2-7448-48CC-AF3E-C39E4C7B3AFD
// Assembly location: F:\tekst\DoingTomorrow\Zenner_Software\program_filer\NFCL_Handler.dll

#nullable disable
namespace NFCL_Handler
{
  internal enum NFCL_Params
  {
    MeterId,
    HardwareTypeId,
    MeterInfoId,
    BaseTypeId,
    MeterTypeId,
    SAP_MaterialNumber,
    SAP_ProductionOrderNumber,
    Printed_serialnumber,
    IdentificationChecksum,
    Bak_TimeZoneInQuarterHours,
    Mbus_ID,
    Mbus_Manufacturer,
    Mbus_Generation,
    Mbus_Medium,
    Mbus_Obis_code,
    cfg_battery_end_life_date,
    cfg_transmission_scenario,
    cfg_otaa_abp_mode,
    cfg_lora_nwkskey,
    cfg_lora_appskey,
    cfg_lora_device_id,
    cfg_loraWan_netid,
    cfg_device_mode,
    protocol_lorawan_version_major,
    protocol_lorawan_version_middle,
    protocol_lorawan_version_minor,
    protocol_lora_version_major,
    protocol_lora_version_minor,
    lora_adr,
    BuildTime,
    Mbus_aes_key,
    Mbus_interval,
    cfg_AccessRadioKey,
    protocol_radio_version_major,
    protocol_radio_version_minor,
    rtc_sys_time,
    radio_center_frequency,
    FD_Mbus_interval,
    radio_transmit_sync1,
    radio_transmit_sync2,
    radio_resceive_sync1,
    radio_resceive_sync2,
    FD_Mbus_nighttime_start,
    FD_Mbus_nighttime_stop,
    FD_Mbus_radio_suppression_days,
    Mbus_nighttime_start,
    Mbus_nighttime_stop,
    Mbus_radio_suppression_days,
    SP9_send_day,
    lora_start_date,
    time_to_send_data,
    cfg_RadioOperationState,
    sp9_subtype,
    cfg_lora_basic_frequency1,
    cfg_lora_basic_frequency2,
    cfg_lora_basic_frequency3,
    cfg_lora_rx_freq_window2,
    con_work_state,
    nfc_ident,
    con_fast_check,
    cfg_lora_deveui,
    cfg_lora_appeui,
    cfg_lora_AppKey,
    radio_frequency_inc_dec,
    radio_band_with,
    radio_afc_band_with,
    radio_tx_data_rate,
    radio_rx_data_rate,
    radio_power,
    radio_frequency_deviation,
    radio_TxBandwithLora,
    radio_carrier_mode,
    radio_reg_tx_bandwith_lora,
    cfg_ModuleCode,
    nfc_err_state,
    CommunicationScenario,
    ndc_lib_version,
  }
}
