// Decompiled with JetBrains decompiler
// Type: THL_Handler.THL_Params
// Assembly: THL_Handler, Version=1.0.5.0, Culture=neutral, PublicKeyToken=f5405c50fba4c3ca
// MVID: C9669406-A704-45DE-B726-D8A41F27FFB8
// Assembly location: F:\tekst\DoingTomorrow\Zenner_Software\program_filer\THL_Handler.dll

#nullable disable
namespace THL_Handler
{
  internal enum THL_Params
  {
    MeterId,
    HardwareTypeId,
    MeterInfoId,
    BaseTypeId,
    MeterTypeId,
    SAP_MaterialNumber,
    SAP_ProductionOrderNumber,
    Printed_serialnumber,
    IdentificationChecksum,
    Bak_TimeZoneInQuarterHours,
    cfg_Mbus_ID,
    cfg_Mbus_Manufacturer,
    Mbus_Generation,
    Mbus_Medium,
    Mbus_Obis_code,
    cfg_battery_end_life_date,
    cfg_lora_appeui,
    cfg_transmission_scenario,
    cfg_communication_scenario,
    cfg_lora_deveui,
    cfb_lora_AppKey,
    cfg_otaa_abp_mode,
    cfb_lora_nwkskey,
    cfb_lora_appskey,
    cfg_lora_device_id,
    cfg_loraWan_netid,
    cfg_device_mode,
    protocol_lorawan_version_major,
    protocol_lorawan_version_middle,
    protocol_lorawan_version_minor,
    protocol_lora_version_major,
    protocol_lora_version_minor,
    device_status,
    lora_adr,
    FD_Mbus_ID,
    FD_Mbus_Manufacturer,
    FD_Lora_DevEUI,
    BuildTime,
    Mbus_aes_key,
    Mbus_interval,
    FD_LoRa_AppEUI,
    FD_LoRa_AppKey,
    cfg_AccessRadioKey,
    protocol_radio_version_major,
    protocol_radio_version_minor,
    rtc_sys_time,
    radio_center_frequency,
    FD_Mbus_interval,
    radio_transmit_sync1,
    radio_transmit_sync2,
    radio_resceive_sync1,
    radio_resceive_sync2,
    FD_Mbus_nighttime_start,
    FD_Mbus_nighttime_stop,
    FD_Mbus_radio_suppression_days,
    Mbus_nighttime_start,
    Mbus_nighttime_stop,
    Mbus_radio_suppression_days,
    SP9_send_day,
    sp9_subtype,
    lora_start_date,
    time_to_send_data,
    cfg_RadioOperationState,
    mount_switch_state,
    th_reading,
    radio_transmit,
    Mbus_Manufacturer,
  }
}
