// Decompiled with JetBrains decompiler
// Type: M8_Handler.M8_Params
// Assembly: M8_Handler, Version=2.0.6.0, Culture=neutral, PublicKeyToken=f5405c50fba4c3ca
// MVID: 582F1296-F274-42DF-B72B-4C0B4D92AA72
// Assembly location: F:\tekst\DoingTomorrow\Zenner_Software\program_filer\M8_Handler.dll

#nullable disable
namespace M8_Handler
{
  internal enum M8_Params
  {
    MeterId,
    HardwareTypeId,
    MeterInfoId,
    BaseTypeId,
    MeterTypeId,
    SAP_MaterialNumber,
    SAP_ProductionOrderNumber,
    Printed_serialnumber,
    IdentificationChecksum,
    Bak_TimeZoneInQuarterHours,
    Mbus_ID,
    Mbus_Manufacturer,
    Mbus_Generation,
    Mbus_Medium,
    Mbus_Obis_code,
    runtime_flags,
    ntc_remote_t,
    ntc_hs_t,
    ntc_rs_t,
    tamper_switch_state,
    hca_reading,
    cfg_battery_end_life_date,
    cfg_lora_appeui,
    cfg_transmission_scenario,
    cfg_Key_date,
    cfg_hca_config,
    cfg_hca_K,
    cfg_hca_winter_start,
    cfg_hca_summer_start,
    cfg_lora_deveui,
    cfb_lora_AppKey,
    cfg_hca,
    cfg_otaa_abp_mode,
    cfb_lora_nwkskey,
    cfb_lora_appskey,
    cfg_lora_device_id,
    cfg_loraWan_netid,
    cfg_device_mode,
    protocol_lorawan_version_major,
    protocol_lorawan_version_middle,
    protocol_lorawan_version_minor,
    protocol_lora_version_major,
    protocol_lora_version_minor,
    device_status,
    lora_adr,
    cfg_hca_measure_start,
    FD_Mbus_ID,
    FD_Mbus_Manufacturer,
    FD_Mbus_Generation,
    FD_Mbus_Medium,
    FD_Obis_code,
    FD_Lora_DevEUI,
    BuildTime,
    Mbus_aes_key,
    Mbus_interval,
    FD_LoRa_AppEUI,
    FD_LoRa_AppKey,
    cfg_AccessRadioKey,
    protocol_radio_version_major,
    protocol_radio_version_minor,
    rtc_sys_time,
    radio_center_frequency,
    FD_Mbus_interval,
    radio_transmit_sync1,
    radio_transmit_sync2,
    radio_resceive_sync1,
    radio_resceive_sync2,
    FD_Mbus_nighttime_start,
    FD_Mbus_nighttime_stop,
    FD_Mbus_radio_suppression_days,
    Mbus_nighttime_start,
    Mbus_nighttime_stop,
    Mbus_radio_suppression_days,
    SP9_send_day,
    lora_start_date,
    time_to_send_data,
    cfg_RadioOperationState,
    Device_With_TRX,
    FD_Radio3_ID,
  }
}
