// Decompiled with JetBrains decompiler
// Type: MinomatHandler.SCGiCommand
// Assembly: MinomatHandler, Version=1.0.3.0, Culture=neutral, PublicKeyToken=f5405c50fba4c3ca
// MVID: 7EF7C01F-958A-42C5-BD1F-5A50D1BCE76C
// Assembly location: F:\tekst\DoingTomorrow\Zenner_Software\program_filer\MinomatHandler.dll

#nullable disable
namespace MinomatHandler
{
  public enum SCGiCommand
  {
    MinomatV4,
    Minol,
    Firmware,
    LPSR,
    GSM,
    SCGi1_9,
    ComServer,
    RegisteredSlavesIntegrated,
    RegisteredSlavesNotIntegrated,
    ResetConfigurationState,
    MinolId,
    NodeId,
    NetworkId,
    SystemTime,
    RadioChannel,
    TransceiverChannelId,
    RoutingTable,
    FirmwareVersion,
    UserappName,
    FirmwareBuildTime,
    UserappBuildTime,
    ErrorFlags,
    TransmissionPower,
    MultiChannelSettings,
    TransceiverFrequencyOffset,
    TemperatureOffset,
    PhaseDetailsBuffer,
    PhaseDetails,
    RestartMinomat,
    MessUnitNumberMax,
    MaxMessUnitNumberNotConfigured,
    Scenario,
    StartTestReception,
    TestReceptionResult,
    RegisterMessUnit,
    ResetConfiguration,
    StartNetworkSetup,
    DeleteMessUnit,
    InfoOfRegisteredMessUnit,
    RegisteredMessUnits,
    SimPin,
    MasterMinolID,
    APN,
    GPRSUserName,
    GPRSPassword,
    HttpServer,
    HttpResourceName,
    StartGSMTestReception,
    GSMTestReceptionState,
    ForceNetworkOptimization,
    StartNetworkOptimization,
    RegisterOrDeregisterSlave,
    RegisteredSlaves,
    Flash,
    Eeprom,
    AppInitialSettings,
    ActionTimepoint,
    MeasurementData,
    HttpState,
    GsmState,
    ModemBuildDate,
    StartHttpConnection,
    ConfigurationString,
    SwitchToNetworkModel,
    GetComServerFile,
    SetComServerFile,
    MessUnitMetadata,
    ActivateModemAT_Mode,
    LED,
    ModemUpdateImageClear,
    ModemUpdate,
    ModemReboot,
    ModemCounter,
    TcpConfiguration,
    SendSMS,
    ModemDueDate,
    GsmLinkQuality,
    ModemUpdateTiming,
    ModemUpdateTest,
  }
}
