// Decompiled with JetBrains decompiler
// Type: ZR_ClassLibrary.EquipmentTypes
// Assembly: ZR_ClassLibrary, Version=6.16.22.24524, Culture=neutral, PublicKeyToken=f5405c50fba4c3ca
// MVID: EF8F26C8-41DE-4472-B020-D54F7F8B6357
// Assembly location: F:\tekst\DoingTomorrow\Zenner_Software\program_filer\ZR_ClassLibrary.dll

#nullable disable
namespace ZR_ClassLibrary
{
  public enum EquipmentTypes
  {
    UnKnown,
    Hardwaretest,
    PruefboxWaermezaehler,
    AbgleichboxWaermezaehler,
    Pruefstelle,
    EnergiePruefadapterZelsius,
    Pruefplatz,
    AbschlussTestEinrichtungZelsius,
    Widerstandspaar,
    Modultest,
    FunkabgleichEHCAII,
    EndtestEHCAII,
    Produktionsort,
    KonfigurationEHCAII,
    KapseltestZelsius,
    WaterSupplyLocation,
    WaterTestbench,
    HydraulikTestbench,
    RelaisPruefboxFuerFunkmodule,
    AutoPruefboxFuerWaermezaehler,
    EnergiePruefadapterWR3,
    AbschlusstesteinrichtungWR3,
    AutoTestBox,
    AirTestBench,
    SerialPortConfiguration,
    MinoMessTestbench,
    PT100Sensor,
    PT500Sensor,
    PT1000Sensor,
    EnergyTestbenchWithBathes,
    C5DeviceTest,
    C5Hardwaretest,
    C5PrintStation,
    EDCHardwareTestbench,
    LaudaBath,
    PicoPT104Card,
    PicoPT104CardChannel,
    ResistanceNormal,
    Multimeter,
    EDCEndTest,
    EDCPCBAdapterRadio,
    EDCPCBAdapterMBusPuls,
    EDCFunctionTestAdapter,
    C5ScanUnitTestbench,
    C5VolumeMeterTestbench,
    C5UsVmFunctionTest,
    TransducerTestTestbench,
    UsVmCheckTestbench,
    SDPCBTest_T1,
    SDFunctionTest_T2,
    SDTunnelTest_T3,
    SDFinalTest_T5,
    SDAgingTest_T4,
    PDCFactoryTest,
    PDCFinalTest,
    EvmRhFactory,
    EdcReferenceWaterMeter,
    TransducerAssemblingTestbench,
    CoverPrinter,
    THFunctionTest,
    WR4Hardwaretest,
    WR4PrintStation,
    M8TestBenchT1,
    M8TestBenchT2,
    M8TestBenchT3,
    M8TestBenchT4,
    M8TestBenchT5,
    WR4DeviceTest,
    NFCCouplerTest,
    TestbenchPC,
    EnergyTestbenchWithTestbox,
    IUWHardwareTest,
    USTouchPad,
    SingleJetQ2Q1,
    SingleJetQ3,
    MultipleJet,
    DeveloperTestbench,
    PloumeterTestBench,
  }
}
