// Decompiled with JetBrains decompiler
// Type: ZR_ClassLibrary.S3_MemorySegment
// Assembly: ZR_ClassLibrary, Version=6.16.22.24524, Culture=neutral, PublicKeyToken=f5405c50fba4c3ca
// MVID: EF8F26C8-41DE-4472-B020-D54F7F8B6357
// Assembly location: F:\tekst\DoingTomorrow\Zenner_Software\program_filer\ZR_ClassLibrary.dll

#nullable disable
namespace ZR_ClassLibrary
{
  public enum S3_MemorySegment
  {
    LinkedRam,
    InfoMemory,
    BackupStorage0,
    Backup0,
    BackupRuntimeVars0,
    BackupStorage1,
    Backup1,
    BackupRuntimeVars1,
    RAM,
    LinkedVars,
    Backup,
    BackupRuntimeVars,
    RuntimeVars,
    FlashBlock0,
    ProtectedConfigValues,
    WriteProt,
    WriteProtTable,
    ProtectedDisplayCode,
    FlashBlock1,
    ConfigValues,
    FunctionTable,
    DisplayCode,
    ResetRuntimeCode,
    MesurementRuntimeCode,
    CycleRuntimeCode,
    MBusRuntimeCode,
    RuntimeConstants,
    FlashBlock2,
    LoggerTable,
    LoggerHeader,
    LoggerChanal,
    LoggerChanalData,
    TransmitParameterTable,
    FlashBlock3,
    LoggerData,
    CompleteMeter,
    Parameter,
    FunctionLayer,
    Function,
    DisplayFunction,
    FixedBlock,
    PointerBlock,
    JumperBlock,
    LoggerRamData,
    RuntimeCode,
    DisplayMenu,
    DisplayJumpBlock,
    Pointer,
    DataBlock,
    DataTransmitter,
    MBusList,
    MBusTransmitter,
    MBusParameter,
    RadioTransmitter,
    RadioListHeader,
    RadioListHeaderItem,
    RadioParameterList,
    ListLink,
    Heap,
    MBusParameterGroup,
    RadioList,
    HandlerInfos,
  }
}
